04-08 17:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-08 17:06:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-08 17:06:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
04-08 17:08:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-08 17:08:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-08 17:08:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
<<<<<<< HEAD
04-08 17:19:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-08 17:19:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-08 17:19:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
04-09 12:38:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-09 12:38:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-09 12:38:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
04-09 12:40:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "IF" nicht gefunden
Column "IF" not found; SQL statement:
SELECT if FROM Powders WHERE color="red" [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at dbconnection.DBConnection.executeSQLStatement(DBConnection.java:64)
	at xmlparse.MySAXParser.selectFromDb(MySAXParser.java:151)
	at xmlparse.MySAXParser.runExample(MySAXParser.java:56)
	at Test.main(Test.java:25)
04-09 12:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "IF" nicht gefunden
Column "IF" not found; SQL statement:
SELECT if FROM Powders WHERE color="red" [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at dbconnection.DBConnection.executeSQLStatement(DBConnection.java:64)
	at xmlparse.MySAXParser.selectFromDb(MySAXParser.java:152)
	at xmlparse.MySAXParser.runExample(MySAXParser.java:56)
	at Test.main(Test.java:25)
04-09 12:41:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "IF" nicht gefunden
Column "IF" not found; SQL statement:
SELECT if FROM Powders WHERE color="red" [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:75)
	at dbconnection.DBConnection.executeSQLStatement(DBConnection.java:64)
	at xmlparse.MySAXParser.selectFromDb(MySAXParser.java:152)
	at xmlparse.MySAXParser.runExample(MySAXParser.java:56)
	at Test.main(Test.java:25)
04-09 12:42:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SELECT FROM POWDERS WHERE[*] COLOR=""red"" "; erwartet "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "SELECT FROM POWDERS WHERE[*] COLOR=""red"" "; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
SELECT FROM Powders WHERE color="red" [42001-176]
04-09 12:44:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SELECT FROM POWDERS WHERE[*] COLOR='red' "; erwartet "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "SELECT FROM POWDERS WHERE[*] COLOR='red' "; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
SELECT FROM Powders WHERE color='red' [42001-176]
04-09 12:49:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; erwartet "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:

                SELECT FROM Powders WHERE color='red'
           [42001-176]
04-09 12:50:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; erwartet "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:

                SELECT FROM Powders WHERE color='red'
           [42001-176]
04-09 12:51:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; erwartet "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"
Syntax error in SQL statement "
                SELECT FROM POWDERS WHERE[*] COLOR='red'
           "; expected "., (, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:

                SELECT FROM Powders WHERE color='red'
           [42001-176]
04-09 12:55:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SELECT * FROM EFFECTS P2E POWDERS[*]"
Syntax error in SQL statement "SELECT * FROM EFFECTS P2E POWDERS[*]"; SQL statement:
SELECT * FROM EFFECTS P2E POWDERS [42000-186]
04-09 12:55:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SELECT * FROM EFFECTS P2E POWDERS[*]"
Syntax error in SQL statement "SELECT * FROM EFFECTS P2E POWDERS[*]"; SQL statement:
SELECT * FROM EFFECTS P2E POWDERS [42000-186]
=======
<<<<<<< HEAD
04-09 12:33:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-09 12:33:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-09 12:33:35 jdbc[3]: exception
=======
04-09 11:13:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-09 11:13:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-09 11:13:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
04-09 12:31:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "POWDERS" besteht bereits
Table "POWDERS" already exists; SQL statement:
CREATE TABLE Powders(id int not null primary key, pname varchar(100), color varchar(50), price int) [42101-176]
04-09 12:31:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "EFFECTS" besteht bereits
Table "EFFECTS" already exists; SQL statement:
CREATE TABLE Effects(id int not null primary key, ename varchar(100), description varchar(1000)) [42101-176]
04-09 12:31:46 jdbc[3]: exception
>>>>>>> 4f008c77db55dc7d85aaefae7ff432e8b83d5c68
org.h2.jdbc.JdbcSQLException: Tabelle "P2E" besteht bereits
Table "P2E" already exists; SQL statement:
CREATE TABLE p2e(pid int  not null, eid int not null, strength int, PRIMARY KEY (pid, eid), FOREIGN KEY (pid) REFERENCES Powders(id), FOREIGN KEY (eid) REFERENCES Effects(id)) [42101-176]
>>>>>>> 05c4cbaf8d97b4bb1e922172074ca3f233701815
04-17 15:40:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "
          CREATE TABLE SUPERHERO (
            ALIAS VARCHAR(255) NOT NULL REFERENCES POWEREDPERSON(ALIAS) PRIMARY[*] KEY,
            CAPE BOOLEAN
          );
         "; erwartet "INDEX, ON, NOT, DEFERRABLE, ,, )"
Syntax error in SQL statement "
          CREATE TABLE SUPERHERO (
            ALIAS VARCHAR(255) NOT NULL REFERENCES POWEREDPERSON(ALIAS) PRIMARY[*] KEY,
            CAPE BOOLEAN
          );
         "; expected "INDEX, ON, NOT, DEFERRABLE, ,, )"; SQL statement:

          CREATE TABLE SuperHero (
            alias VARCHAR(255) NOT NULL REFERENCES PoweredPerson(alias) PRIMARY KEY,
            cape BOOLEAN
          );
         [42001-176]
04-17 15:40:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "SUPERHERO" nicht gefunden
Table "SUPERHERO" not found; SQL statement:
INSERT INTO SuperHero VALUES ('Wonderboy', NULL); [42102-176]
04-17 15:40:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "
          CREATE TABLE SUPERVILLAIN (
            ALIAS VARCHAR(255) NOT NULL REFERENCES POWEREDPERSON(ALIAS) PRIMARY[*] KEY
          );
         "; erwartet "INDEX, ON, NOT, DEFERRABLE, ,, )"
Syntax error in SQL statement "
          CREATE TABLE SUPERVILLAIN (
            ALIAS VARCHAR(255) NOT NULL REFERENCES POWEREDPERSON(ALIAS) PRIMARY[*] KEY
          );
         "; expected "INDEX, ON, NOT, DEFERRABLE, ,, )"; SQL statement:

          CREATE TABLE SuperVillain (
            alias VARCHAR(255) NOT NULL REFERENCES PoweredPerson(alias) PRIMARY KEY
          );
         [42001-176]
04-17 15:40:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "SUPERVILLAIN" nicht gefunden
Table "SUPERVILLAIN" not found; SQL statement:
INSERT INTO SuperVillain VALUES ('Magneto'); [42102-176]
04-17 15:40:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "SUPERHERO" nicht gefunden
Table "SUPERHERO" not found; SQL statement:

            SELECT *
            FROM SuperHero
            WHERE cape = 'FALSE';
           [42102-176]
04-17 15:40:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "SUPERHERO" nicht gefunden
Table "SUPERHERO" not found; SQL statement:

            WITH no_alias_count (comic_no, alias, count) AS (
              SELECT no AS comic_no, h.alias, COUNT(power) AS count
              FROM comic
                JOIN HasPowerSince AS h ON comic <= no
                JOIN SuperHero AS s ON h.alias = s.alias
              WHERE no BETWEEN 10
                AND 20 GROUP BY no, h.alias
            )
            SELECT title, alias, count
            FROM no_alias_count
              JOIN comic ON comic_no = no;
           [42102-176]
04-17 15:53:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "CREATE TABLE TASK(
    NAME VARCHAR(200) PRIMARY KEY
),[*] "
Syntax error in SQL statement "CREATE TABLE TASK(
    NAME VARCHAR(200) PRIMARY KEY
),[*] "; SQL statement:
CREATE TABLE Task(
    name varchar(200) PRIMARY KEY
), [42000-176]
04-17 16:00:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Schema "TASK" nicht gefunden
Schema "TASK" not found; SQL statement:
CREATE TABLE PLAYER(
    id int(10) PRIMARY KEY,
    task_id int(10) NOT NULL,
    FOREIGN KEY (task_id) REFERENCES TASK.id
) [90079-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.getSchema(Parser.java:655)
	at org.h2.command.Parser.getSchema(Parser.java:662)
	at org.h2.command.Parser.parseReferences(Parser.java:5635)
	at org.h2.command.Parser.parseAlterTableAddConstraintIf(Parser.java:5609)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5717)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:39:46 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:40:02 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO Task VALUES (1, "test", "testDb", "true", 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO TASK VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:17 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO TASK VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:17 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO TASK VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:17 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO TASK VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "test" nicht gefunden
Column "test" not found; SQL statement:
INSERT INTO TASK (id, name, db_name, db_mem, players) VALUES (1, "test", "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:48 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "testDb" nicht gefunden
Column "testDb" not found; SQL statement:
INSERT INTO TASK VALUES (1, 2, "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:49 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "testDb" nicht gefunden
Column "testDb" not found; SQL statement:
INSERT INTO TASK VALUES (1, 2, "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:49 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "testDb" nicht gefunden
Column "testDb" not found; SQL statement:
INSERT INTO TASK VALUES (1, 2, "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-17 16:41:49 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Feld "testDb" nicht gefunden
Column "testDb" not found; SQL statement:
INSERT INTO TASK VALUES (1, 2, "testDb", true, 124) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
04-20 14:47:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen
The object is already closed [90007-176]
04-20 14:47:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE TASK SET PLAYERS= "; erwartet "DEFAULT, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "UPDATE TASK SET PLAYERS= "; expected "DEFAULT, NOT, EXISTS, INTERSECTS"; SQL statement:
UPDATE Task SET players= [42001-176]
04-20 14:49:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Das Objekt wurde bereits geschlossen
The object is already closed [90007-176]
04-20 14:50:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "UPDATE TASK SET PLAYERS= "; erwartet "DEFAULT, NOT, EXISTS, INTERSECTS"
Syntax error in SQL statement "UPDATE TASK SET PLAYERS= "; expected "DEFAULT, NOT, EXISTS, INTERSECTS"; SQL statement:
UPDATE Task SET players= [42001-176]
04-20 22:40:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Anzahl der Felder stimmt nicht überein
Column count does not match; SQL statement:
INSERT INTO Task VALUES('test', 'test', false) [21002-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.command.dml.Insert.prepare(Insert.java:266)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:128)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:117)
	at dbconnection.DBConnection.executeSQLUpdateStatement(DBConnection.java:93)
	at sandbox.Task.createTask(Task.java:86)
	at sandbox.Game.<init>(Game.java:32)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
04-20 22:44:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unerlaubter Wert "0" für Parameter "columnIndex"
Invalid value "0" for parameter "columnIndex" [90008-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:227)
	at org.h2.jdbc.JdbcResultSetMetaData.checkColumnIndex(JdbcResultSetMetaData.java:449)
	at org.h2.jdbc.JdbcResultSetMetaData.getColumnName(JdbcResultSetMetaData.java:87)
	at dbconnection.DBConnection.transformResultSet(DBConnection.java:255)
	at dbconnection.DBConnection.executeSQLSelectPreparedStatement(DBConnection.java:170)
	at sandbox.Task.checkTask(Task.java:104)
	at sandbox.Game.<init>(Game.java:21)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
04-20 22:45:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unerlaubter Wert "0" für Parameter "columnIndex"
Invalid value "0" for parameter "columnIndex" [90008-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:227)
	at org.h2.jdbc.JdbcResultSetMetaData.checkColumnIndex(JdbcResultSetMetaData.java:449)
	at org.h2.jdbc.JdbcResultSetMetaData.getColumnName(JdbcResultSetMetaData.java:87)
	at dbconnection.DBConnection.transformResultSet(DBConnection.java:255)
	at dbconnection.DBConnection.executeSQLSelectPreparedStatement(DBConnection.java:170)
	at sandbox.Task.checkTask(Task.java:104)
	at sandbox.Game.<init>(Game.java:21)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
04-20 22:52:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unerlaubter Wert "5" für Parameter "parameterIndex"
Invalid value "5" for parameter "parameterIndex" [90008-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:227)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1383)
	at org.h2.jdbc.JdbcPreparedStatement.setString(JdbcPreparedStatement.java:353)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:208)
	at sandbox.Task.updateTask(Task.java:80)
	at sandbox.Game.<init>(Game.java:28)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
04-22 16:02:00 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:02:00 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:02:00 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:02:00 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:02:00 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:02:02 jdbc[3]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdateStatement(DBConnection.java:138)
	at xmlparse.MySAXParser.insertToDb(MySAXParser.java:163)
	at xmlparse.MySAXParser.parseAndCreateDb(MySAXParser.java:95)
	at sandbox.Task.createTask(Task.java:202)
	at sandbox.Game.startGame(Game.java:61)
	at Test.main(Test.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:25 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:25 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:25 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:25 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:25 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:03:28 jdbc[3]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:101)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:119)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdateStatement(DBConnection.java:138)
	at xmlparse.MySAXParser.insertToDb(MySAXParser.java:163)
	at xmlparse.MySAXParser.parseAndCreateDb(MySAXParser.java:95)
	at sandbox.Task.createTask(Task.java:202)
	at sandbox.Game.startGame(Game.java:61)
	at Test.main(Test.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)

org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:04:41 jdbc[3]: null
org.h2.message.DbException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.message.DbException.get(DbException.java:143)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at dbconnection.DBConnection.executeSQLUpdatePreparedStatement(DBConnection.java:210)
	at sandbox.Task.closeTask(Task.java:219)
	at sandbox.Game.endGame(Game.java:83)
	at Test.main(Test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Die Datenbank-Verbindung wurde nicht explizit geschlossen (jetzt in der Müllabfuhr)
The connection was not closed by the application and is garbage collected [90018-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 26 more
04-22 16:44:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "MOVIE" nicht gefunden
Table "MOVIE" not found; SQL statement:
SELECT Avg(box_office_takings) average
				FROM movie
				GROUP BY mid [42102-176]
05-07 16:55:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:72)
	at Test.main(Test.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:01:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:30:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:31:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:31:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:49:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:53:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 17:56:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
05-07 18:05:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feld "FDFEWDF" nicht gefunden
Column "FDFEWDF" not found; SQL statement:
SELECT FDFEWdf [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Select.prepare(Select.java:831)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at de.tu_bs.cs.ifis.sqlgame.dbconnection.DBConnection.checkSQLSyntax(DBConnection.java:78)
	at Test.main(Test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:72)
	at sbt.Run.run0(Run.scala:65)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:54)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:58)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)
